##
## Created by ruslan.nikolaev on 11/18/18.
##

TaskConfig:
  SIGMA_L: 0.3
  SIGMA_H: 0.5
  SIGMA_IOU: 0.3
  T_MIN: 5

  INPUT_W: 416
  INPUT_H: 416

  DATA_DIR: "data/files.txt"
  IMG_LIMIT: 1
  IN_LAYER: "inputs"
  OUT_LAYER: "output_boxes"
  GRAPH_PATH: "graphs/frozen_darknet_yolov3_model.pb"
  CLS_PATH: "config/obj.names"
  MODEL_CKPT_PATH: "models/tiny/model.ckpt"
